name: Node.js - Test and Deploy

on:
  push:
    branches:
     - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
    - run: yarn install

    - name: Test Stage
      run: yarn test

    - name: Build Stage
      run: yarn build
      
    - name: Build Storybook
      run: yarn build-storybook
      
    - name: Deploy to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
